function [Hz, trialLength, nClass, subID, numTrials, RS_len, accumilationFlag]...
    = parameter_gui(ChunkDelayobj, AMPobj, IMPobj, RestDelayobj, system)

% Set figure
S.fh    = figure('units','normalized',...                   
    'position',[0.2 0.3 0.5 0.4],...
    'menubar','none',...
    'name','Parameter setting',...
    'numbertitle','off',...
    'resize','off');

% Set title text
S.title = uicontrol('style','text',...                 
                     'unit','normalized',...
                     'position',[0.2 0.7 0.6 0.15],...
                     'string','Set parameters for your system');

% Set confirmation button
S.pb    = uicontrol('style','push',...                  
    'unit','normalized',...
    'position',[0.75 0.1 0.2 0.1],...
    'string','Ok');

% Set subID text
S.subIDtxt = uicontrol('style','text',...                 
    'unit','normalized',...
    'position',[0.05 0.6 0.15 0.1],...
    'string','Subject ID:');

% Set subID options
S.subID	= uicontrol('style','edit',...                  
    'unit','normalized',...
    'position',[0.2 0.62 0.1 0.1],...
    'string','777');

% Set number of classes text
S.nClstxt = uicontrol('style','text',...                 
    'unit','normalized',...
    'position',[0.05 0.4 0.15 0.1],...
    'string','# of classes:');

% Set number of classes options
S.nCls  = uicontrol('style','edit',...                  
    'unit','normalized',...
    'position',[0.2 0.42 0.1 0.1],...
    'string','3');

% Set impedance button
S.Imp = uicontrol('style','push',...              
    'unit','normalized',...
    'position',[0.125 0.2 0.15 0.15],...
    'string','Impedance');

% Set resting state length text
S.RStxt = uicontrol('style','text',...                 
    'unit','normalized',...
    'position',[0.35 0.6 0.15 0.1],...
    'string','Resting-state length (sec):');

% Set resting state length options
S.RSlength = uicontrol('style','edit',...                 
    'unit','normalized',...
    'position',[0.5 0.62 0.15 0.1],...
    'string','60');

% Set signal length text
S.Chunktxt = uicontrol('style','text',...                 
    'unit','normalized',...
    'position',[0.35 0.4 0.15 0.1],...
    'string','Chunk size (sec):');

% Set signal length options
S.ChunkSz = uicontrol('style','edit',...                  
    'unit','normalized',...
    'position',[0.5 0.42 0.15 0.1],...
    'string','6');

% For non-communication systems
if ~strcmpi(system, 'Communication')
    
    % Set num of trials text
    S.nTrialtxt = uicontrol('style','text',...
        'unit','normalized',...
        'position',[0.65 0.6 0.15 0.1],...
        'string','# of trials:');
    
    % Set num of trials options
    S.nTrial = uicontrol('style','edit',...
        'unit','normalized',...
        'position',[0.8 0.62 0.15 0.1],...
        'string','20');
end

% Set Hz text
S.Hztxt = uicontrol('style','text',...                 
    'unit','normalized',...
    'position',[0.65 0.4 0.15 0.1],...
    'string','Sampling rate:');

% Set Hz options
S.Hz    = uicontrol('style','popupmenu',...             
    'unit','normalized',...
    'position',[0.8 0.42 0.15 0.1],...
    'string',['512';'256']);

% For online system only
if strcmpi(system, 'Online')
    
    % Set accumilation text
    S.Accumtxt = uicontrol('style','text',...                 
        'unit','normalized',...
        'position',[0.4 0.2 0.1 0.1],...
        'string','Accumilation:');
    
    % Set accumilation checkbox
    S.accumbx = uicontrol('style','checkbox',...              
        'unit','normalized',...
        'Value', 1, ...
        'position',[0.525 0.22 0.1 0.1]);
end

% Set the callback, pass hands.
set(S.Imp,'callback',{@Utillity.Impedance_call,IMPobj});       
    
% Set the callback, pass hands.
set(S.pb,'callback',{@Utillity.pb_call,system,ChunkDelayobj,AMPobj,RestDelayobj,S});   

uiwait(S.fh);                                       % wait for user reaction
    
[Hz, trialLength, nClass, subID, numTrials, RS_len, accumilationFlag] ...
    = Utillity.extract_parameters(S, system); % extract user input parameters

close(S.fh);                                        % close figure

end