function [Hz, trialLength, nClass, subID, numTrials, RS_len, accumilationFlag]...
    = parameter_gui(ChunkDelayobj, AMPobj, IMPobj, RestDelayobj, system)
% PARAMETER_GUI Creates a GUI for the user to choose desireable parameters,
% including:
%     - Subject's number.
%     - Number of classes.
%     - Resting state length.
%     - Trial length.
%     - Sampling rate.
%
% For non-communication systems the gui has another option:
%     - number of trials.
%
% For online system the gui has another option:
%     - Accumulating data.
%
% Further more, it is possible to activate the impedance object in Simulink
% from the gui.
%
% Changed parameters are updated in Simulink (if needed).
%
% All parameters are extracted and returned.
%
% INPUT:
%     - ChunkDelayobj - Training delay object's name.
%     - AMPobj - Amplifier object's name.
%     - IMPobj - Impedance object's name.
%     - RestDelayobj - Resting state delay object's name.
%     - system - Desired operated system's name.
%
% OUTPUT:
%     - Hz - Sampling rate.
%     - trialLength - Trial length (in sec).
%     - nClass - Number of classes.
%     - subID - Subject's number.
%     - numTrials - Number of trials (PER CONDITION).
%     - RS_len - Resting state length (in sec).
%     - accumilationFlag - Accumulation flag
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% GUI options

% Set figure
GUI.fh    = figure('units','normalized',...
    'position',[0.2 0.3 0.5 0.4],...
    'menubar','none',...
    'name','Parameter setting',...
    'numbertitle','off',...
    'resize','off');

% Set title text
GUI.title = uicontrol('style','text',...
    'unit','normalized',...
    'position',[0.2 0.7 0.6 0.15],...
    'string','Set parameters for your system');

% Set confirmation button
GUI.pb    = uicontrol('style','push',...
    'unit','normalized',...
    'position',[0.75 0.1 0.2 0.1],...
    'string','Ok');

% Set subID text
GUI.subIDtxt = uicontrol('style','text',...
    'unit','normalized',...
    'position',[0.05 0.6 0.15 0.1],...
    'string','Subject ID:');

% Set subID options
GUI.subID	= uicontrol('style','edit',...
    'unit','normalized',...
    'position',[0.2 0.62 0.1 0.1],...
    'string','777');

% Set number of classes text
GUI.nClstxt = uicontrol('style','text',...
    'unit','normalized',...
    'position',[0.05 0.4 0.15 0.1],...
    'string','# of classes:');

% Set number of classes options
GUI.nCls  = uicontrol('style','edit',...
    'unit','normalized',...
    'position',[0.2 0.42 0.1 0.1],...
    'string','3');

% Set impedance button
GUI.Imp = uicontrol('style','push',...
    'unit','normalized',...
    'position',[0.125 0.2 0.15 0.15],...
    'string','Impedance');

% Set resting state length text
GUI.RStxt = uicontrol('style','text',...
    'unit','normalized',...
    'position',[0.35 0.6 0.15 0.1],...
    'string','Resting-state length (sec):');

% Set resting state length options
GUI.RSlength = uicontrol('style','edit',...
    'unit','normalized',...
    'position',[0.5 0.62 0.15 0.1],...
    'string','1.5');

% Set signal length text
GUI.Chunktxt = uicontrol('style','text',...
    'unit','normalized',...
    'position',[0.35 0.4 0.15 0.1],...
    'string','Chunk size (sec):');

% Set signal length options
GUI.ChunkSz = uicontrol('style','edit',...
    'unit','normalized',...
    'position',[0.5 0.42 0.15 0.1],...
    'string','4');

% Set Hz text
GUI.Hztxt = uicontrol('style','text',...
    'unit','normalized',...
    'position',[0.65 0.4 0.15 0.1],...
    'string','Sampling rate:');

% Set Hz options
GUI.Hz    = uicontrol('style','popupmenu',...
    'unit','normalized',...
    'position',[0.8 0.42 0.15 0.1],...
    'string',['512';'256']);

% For non-communication systems
if ~strcmpi(system, 'Communication')
    
    switch system
        case 'Offline'
            
            trials_N = '15';
            
        case 'Online'
            
            % Set accumilation text
            GUI.Accumtxt = uicontrol('style','text',...
                'unit','normalized',...
                'position',[0.4 0.2 0.1 0.1],...
                'string','Accumilation:');
            
            % Set accumilation checkbox
            GUI.accumbx = uicontrol('style','checkbox',...
                'unit','normalized',...
                'Value', 0, ...
                'position',[0.525 0.22 0.1 0.1]);
            
            trials_N = '8';
    end
    
    % Set num of trials text
    GUI.nTrialtxt = uicontrol('style','text',...
        'unit','normalized',...
        'position',[0.65 0.6 0.15 0.1],...
        'string','# of trials:');
    
    % Set num of trials options
    GUI.nTrial = uicontrol('style','edit',...
        'unit','normalized',...
        'position',[0.8 0.62 0.15 0.1],...
        'string',trials_N);
end

%% GUI callbacks

% Set the callback, pass hands.
set(GUI.Imp,'callback',{@Utillity.Impedance_call,IMPobj});

% Set the callback, pass hands.
set(GUI.pb,'callback',{@Utillity.pb_call,system,ChunkDelayobj,AMPobj,RestDelayobj,GUI});

%% Wait for user reaction

uiwait(GUI.fh);

%% Extract user input parameters
[Hz, trialLength, nClass, subID, numTrials, RS_len, accumilationFlag] ...
    = Utillity.extract_parameters(GUI, system);

%% Close GUI
close(GUI.fh);

end